version: '3.8'

services:
  spring-gateway:
    build:
      context: ./scg
      dockerfile: Dockerfile
    container_name: scg-container
    ports:
      - "8080:8080"
    depends_on:
      - fastapi-node-1
      - fastapi-node-2
      - react-front
    environment:
      - API_KEY=${API_KEY}
    networks:
      - backend-network

  react-front:
    build:
      context: ./front/my-react-front
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: react-container
    ports:
      - "80:80"
    networks:
      - backend-network

  fastapi-node-1:
    build:
      context: ./fastapi/fastapi_1
      dockerfile: Dockerfile
    container_name: fastapi-container-1
    ports:
      - "8001:8000"
    environment:
      - SERVER_NAME=FastAPI-Server-1
      - API_KEY=${API_KEY}
      - MONGO_DETAILS=${MONGO_DETAILS}
      - HF_HOME=/root/.cache/huggingface
      - HF_TOKEN=${HF_TOKEN}
    networks:
      - backend-network
    volumes:
      - ./fastapi/fastapi_1:/app
      - thumbnail_data:/app/thumbnails
      - hf_cache:/root/.cache/huggingface
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  fastapi-node-2:
    build:
      context: ./fastapi/fastapi_1
      dockerfile: Dockerfile
    container_name: fastapi-container-2
    ports:
      - "8002:8000"
    environment:
      - SERVER_NAME=FastAPI-Server-2
      - API_KEY=${API_KEY}
      - MONGO_DETAILS=${MONGO_DETAILS}
      - HF_HOME=/root/.cache/huggingface
      - HF_TOKEN=${HF_TOKEN}
    networks:
      - backend-network
    volumes:
      - ./fastapi/fastapi_1:/app
      - thumbnail_data:/app/thumbnails
      - hf_cache:/root/.cache/huggingface
    command: uvicorn app:app --host 0.0.0.0 --port 8000

networks:
  backend-network:
    driver: bridge

volumes:
  thumbnail_data:
  hf_cache: