server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*" # X-API-Key ??? ?? ??

      routes:
        - id: old-fastapi-test
          uri: http://localhost:8000
          predicates:
            - Path=/api/fashion/**
          filters:
            # /test/infer ? ???? /infer ? ??? FastAPI? ????
            - RewritePath=/api/fashion/(?<segment>.*), /$\{segment}