server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost"
              - "http://localhost:80"
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # 로드 밸런싱 일단 2개
        - id: fastapi-node-1-route
          uri: http://fastapi-node-1:8000
          predicates:
            - Path=/garments/**, /recommend, /analyze, /health, /ui
            - Weight=ai-group, 5
          filters:
            - AddRequestHeader=X-API-Key, ${API_KEY:default-key}

        - id: fastapi-node-2-route
          uri: http://fastapi-node-2:8000
          predicates:
            - Path=/garments/**, /recommend, /analyze, /health, /ui
            - Weight=ai-group, 5
          filters:
            - AddRequestHeader=X-API-Key, ${API_KEY:default-key}

        # 정적 썸네일 경로
        - id: fastapi-node-1-thumbnails
          uri: http://fastapi-node-1:8000
          predicates:
            - Path=/thumbnails/**
            - Weight=thumb-group, 5

        - id: fastapi-node-2-thumbnails
          uri: http://fastapi-node-2:8000
          predicates:
            - Path=/thumbnails/**
            - Weight=thumb-group, 5

        - id: react-front-route
          uri: http://react-front:80
          predicates:
            - Path=/**